### ISSUE TITLE
Explain difference of various templates a bit in more details

### ISSUE THREAD

**Issue by rhuss** [syndesisio/openshift-templates#28]
It would be awesome to know a bit more about the differences between the various templates.

I.e.

* Which templates are recommended for the various envs ? (oc cluster up, minishift, deficated)
* What is the difference of the `-dev` and normal variants ?
* What is _functionally_ different in the `-single-tenant` versions (i.e. what is the technical difference e.g. wrt/ security setup).
* What is the advantages of having the non single-tenant variants as it looks like that the later are a subste of the former ? (or in other words: What cannot be done with the single-tenant variants)

Maybe we could even consolidate the template setup to a smaller set so that we are not testing on diverging templates ?

// @jimmidyson you are probably the only one who can answer these ;-)

**Comment by rhuss** [comment]
Just digging a bit myself into the dev vs. non-dev differences:

what | dev | non-dev |
----- | --- | --------|
Images | direct references | image streams, with triggers |
ImagePullPolicy | configurable, `IfNotPresent` by default | Always `IfNotPresent` |
CORS | --- | localhost allowed, too |

**Comment by jimmidyson** [comment]
Just a quick write up while I'm at the airport. Excuse typos :)

These templates vary in small details - this is a problem i have with openshift templates generally, e.g. requiring different templates for persistent storage vs ephemeral. The ideal would be to have one single template but that seems unlikely - ideas to get there would be awesome.

The difference between -dev variants is the use of docker image directly Vs image streams. This allows the use of locally built images e.g. when using minishift or oc cluster up. Image streams reference a specific sha so i don't think can be used in this way. The non-dev variants user image streams so that rolling upgrades can be managed by openshift deploymentconfigs as new versions of images are built and imported.

The only difference between single tenant variants is the exclusion of the global oauth client, instead using a namespaced service account to act as a service account. These guys be consolidated easily and the oauth client be required as prerequisite for multi tenant setups.

Really happy to see proposals to how to consolidate these together, with the proviso that I'd like to keep deployment as simple as possible, preferably just with simple oc command.

**Comment by rhuss** [comment]
Thanks. Let me add this to the README, we can then continue on the PR.

**Comment by rhuss** [comment]
Added a section to the README with the information from here (as I understood it ;-). Please feel free to adapt the README if things changes or a factually wrong.
